/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(c4fm_reencode_soft_decision_cf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bb36249d60a249a2d11a1f1369b6e31a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/decision/c4fm_reencode_soft_decision_cf.h>
// pydoc.h is automatically generated in the build directory
#include <c4fm_reencode_soft_decision_cf_pydoc.h>

void bind_c4fm_reencode_soft_decision_cf(py::module& m)
{

    using c4fm_reencode_soft_decision_cf    = gr::decision::c4fm_reencode_soft_decision_cf;


    py::class_<c4fm_reencode_soft_decision_cf, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<c4fm_reencode_soft_decision_cf>>(m, "c4fm_reencode_soft_decision_cf", D(c4fm_reencode_soft_decision_cf))

        .def(py::init(&c4fm_reencode_soft_decision_cf::make),
           D(c4fm_reencode_soft_decision_cf,make)
        )
        



        ;




}








