/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(c4fm_soft_decision_fc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(46a33a755f9ab3e925545e28d204c9c8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/decision/c4fm_soft_decision_fc.h>
// pydoc.h is automatically generated in the build directory
#include <c4fm_soft_decision_fc_pydoc.h>

void bind_c4fm_soft_decision_fc(py::module& m)
{

    using c4fm_soft_decision_fc    = gr::decision::c4fm_soft_decision_fc;


    py::class_<c4fm_soft_decision_fc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<c4fm_soft_decision_fc>>(m, "c4fm_soft_decision_fc", D(c4fm_soft_decision_fc))

        .def(py::init(&c4fm_soft_decision_fc::make),
           D(c4fm_soft_decision_fc,make)
        )
        



        ;




}








